{{- if .Values.deployments }}{{- range $deployment := .Values.deployments }}
{{- if $deployment.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ $.Release.Name }}-{{ $deployment.name }}"
  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}-{{ $deployment.name }}"
    app.kubernetes.io/name: {{ $deployment.name }}
    app.kubernetes.io/version: {{ $deployment.version | quote }}
    app.kubernetes.io/component: {{ $deployment.component }}
    app.kubernetes.io/part-of: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/environment: {{ $.Values.environment }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ $.Release.Name }}-{{ $deployment.name }}"
  minReplicas: "{{ $deployment.autoscaling.minReplicas }}"
  maxReplicas: "{{ $deployment.autoscaling.maxReplicas }}"
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: "{{ $deployment.autoscaling.cpuUtilization }}"
{{- end }} # endif autoscale
{{- end }}{{- end }} # foreach deployment