images:
- name: Helm Client
  description: Helm is a tool for managing Kubernetes charts. Charts are packages of pre-configured Kubernetes resources.
  provides:
  - helm
  image: docker.io/envcli/helm:2.13.0
  shell: sh
  directory: /data
  cache:
  - name: kubectl
    directory: /root/.kube
  - name: helm
    directory: /root/.helm
