image: docker.io/envcli/envcli:latest

stages:
- deploy

services:
- docker:stable-dind

deploy:
  stage: deploy
  script:
  - helm init --client-only --skip-refresh
  - cd $CI_PROJECT_DIR/flex
  - helm package flex
  - cd $CI_PROJECT_DIR/cronjob
  - helm package cronjob
