###
# EnvCLI
###
image: docker.io/envcli/envcli:latest

###
# Services
###
services:
- docker:stable-dind

###
# Stages
###
stages:
- build
- deploy

###
# Build Charts
###
build:
  stage: build
  before_script:
  - helm init --client-only --skip-refresh
  variables:
    REPO_DIR: $CI_PROJECT_DIR/stable
  script:
  - ./ci/build-charts.sh
  artifacts:
    paths:
    - public

###
# Build & Publish Charts on GitLab Pages
###
pages:
  stage: deploy
  before_script:
  - helm init --client-only --skip-refresh
  script:
  - echo "Publishing `/public` to gitlab pages ..."
  - helm repo index ./public
  artifacts:
    paths:
    - public
  only:
  - master
