apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cronjob.name" . }}
    helm.sh/chart: {{ include "cronjob.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  # cronjob schedule
  schedule: {{ .Values.job.schedule }}
  # Allow parralel execution for this cronjob: Allow, Forbid
  concurrencyPolicy: {{ .Values.job.concurrencyPolicy }}
  # only run within x seconds of the scheduled time, otherwise skip the next execution
  startingDeadlineSeconds: {{ .Values.job.startingDeadlineSeconds }}
  # specify how many completed and failed jobs should be kept in the kubernetes job history
  successfulJobsHistoryLimit: {{ .Values.job.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.job.failedJobsHistoryLimit }}
  # job template
  jobTemplate:
    spec:
      template:
        spec:
          # containers
          containers:
          - name: {{ .Chart.Name }}
            # Image
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            # environment
            {{- if .Values.job.env }}
            env:
{{ toYaml .Values.job.env | indent 14 }}
            {{- end }}
            # resources
            resources:
              {{- toYaml .Values.resources | nindent 12 }}
            # graceful shutdown
            terminationGracePeriodSeconds: {{ .Values.job.terminationGracePeriodSeconds }}
          # image pull secret
          {{- if .Values.image.pullSecret -}}
          imagePullSecrets:
          - name: {{ .Values.image.pullSecret }}
          {{- end }}
          # node selector
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          # affinity
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          # tolerations
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          # restart policy ("OnFailure", "Never")
          restartPolicy: {{ .Values.job.restartPolicy }}
          # Volume Mounts
          {{- if .Values.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 12 }}
          {{- end }}
      ###
      # Begin Volumes
      ###
      {{- if .Values.volumes }}
      volumes:
      {{- range $volume := .Values.volumes }}
      - name: {{ $volume.name }}
        ###
        # Type: ConfigMap
        ###
        {{- if $volume.configMap }}
        configMap:
          # Static Selector: Name
          {{- if $volume.configMap.name }}
          name: {{ $volume.configMap.name }}
          {{- end }}
          # Dynamic Selector: Current Release
          {{- if $volume.configMap.selector }}
          name: "{{ $.Release.Name }}-{{ $volume.configMap.selector }}"
          {{- end }}
        ###
        # Type: HostPath
        ###
        {{- else if $volume.hostPath }}
        hostPath:
          # directory location on host
          path: "{{ $volume.hostPath.path }}"
          # this field is optional
          type: DirectoryOrCreate
        ###
        # Type: EmptyDir
        ###
        {{- else if $volume.emptyDir }}
        emptyDir: {}
        ###
        # PersistentVolumeClaim
        ###
        {{- else if $volume.persistentVolumeClaim }}
        persistentVolumeClaim:
          # Static Selector
          {{- if $volume.persistentVolumeClaim.claimName }}
          claimName: "{{ $volume.persistentVolumeClaim.claimName }}"
          {{- end }}
          # Dynamic Selector
          {{- if $volume.persistentVolumeClaim.claimNameSelector }}
          claimName: "{{ $.Release.Name }}-{{ $volume.persistentVolumeClaim.claimNameSelector }}"
          {{- end }}
        ###
        # Type: Other
        ###
        {{- else }}
{{ toYaml $volume | indent 8 }}
        {{- end }}
      {{- end }}
      ###
      # End Volumes
      ###
