apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "sentry-reporter.labels" . | indent 4 }}
  name: {{ template "sentry-reporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  sentry.dsn: {{ .Values.sentry.dsn | b64enc | quote }}
