{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{ include "sentry-reporter.labels" . | indent 4 }}
  name: {{ template "sentry-reporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
